name: Demo Workflow

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print secret (safe version)
        run: echo "I loaded the secret successfully!"
        env:
          SECRET_VALUE: ${{ secrets.FIRST_NAME }}
