  name: Example Workflow

  on: [push]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print secret value
        run: echo "MY_SECRET_KEY=${{ secrets.FIRST_NAME }}" 

